# -*- coding: utf-8 -*-
"""Boston House Pricing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IK9LIk72DRzIxRnJ921oymx-M_9oNApV
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
# %matplotlib inline

df = pd.read_csv('/content/drive/MyDrive/DATASETS/boston.csv')

boston_keys = ['data', 'target', 'feature_names', 'DESCR', 'filename']

df.head()

df.shape

df.info()

df.describe().round(2)

df.isnull().sum()

df['Price'] = df.pop('MEDV')

df.head()

sns.pairplot(df)

for col in df.columns:
    if col != 'Price':
        plt.figure()
        plt.scatter(df[col], df['Price'])
        plt.xlabel(col)
        plt.ylabel('Price')
        plt.title(f'{col} vs Price')
        plt.show()

for i in df.columns:
  if i != 'Price':
    plt.figure()
    sns.regplot(x=df[i],y=df['Price'])
    plt.show()

X = df.drop('Price', axis=1)
y = df['Price']

X.head()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

model = LinearRegression()
model.fit(X_train, y_train)

print(model.coef_)

print(model.intercept_)

X_test_pred = model.predict(X_test)
plt.scatter(y_test, X_test_pred)

residuals = y_test - X_test_pred
sns.displot(residuals,kind='kde')

print(mean_squared_error(y_test,X_test_pred))
print(r2_score(y_test,X_test_pred))

X.iloc[0].shape

scaler.transform(X.iloc[0].values.reshape(1,-1))

model.predict(scaler.transform(X.iloc[0].values.reshape(1,-1)))

import pickle
pickle.dump(model, open('model.pkl', 'wb'))

pickle_model = pickle.load(open('model.pkl', 'rb'))

pickle_model.predict(scaler.transform(X.iloc[0].values.reshape(1,-1)))





